language: bash

os:
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update            ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install shellcheck; fi

script:
  # Fail if any of these files have warnings
  - shellcheck *.sh
