language: bash

os:
  - linux
  - osx
  - windows

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update; fi

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install shellcheck; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install shellcheck; fi
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install shellcheck; fi

before_script:
  - if [ $TRAVIS_OS_NAME = windows ]; then tr -d '\r' *.sh; fi

script:
  # Fail if any of these files have warnings
  - shellcheck *.sh
