# Windows not currently tested since the following line deletes all content in
# the file instead of just the literal carriage returns

language: bash

os:
  - linux
  - osx
  # - windows

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update; fi

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install shellcheck; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install shellcheck; fi
  # - if [ $TRAVIS_OS_NAME = windows ]; then choco install shellcheck; fi

before_script:
  # - if [ $TRAVIS_OS_NAME = windows ] ; then
  #     for file in $(find $(pwd) -name "*.sh") ; do
  #       tr -d '\r' < $file > $file ;
  #     done ;
  #   fi
  - shellcheck *.sh

script:
  - chmod 700 setup.sh && ./setup.sh
