os:
  - linux
  - osx

addons:
  apt:
    packages:
      - shellcheck

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update            ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install shellcheck; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then apt-get update            ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then apt-get install shellcheck; fi

script:
  # Fail if any of these files have warnings
  - shellcheck *.sh
