name: Auto-bump Version

on:
  issue_comment:
    types: ["created"]

jobs:
  bump-version:
    if: (
          (github.event.issue.pull_request != null) &&
          contains(github.event.comment.body, '/bump-version')
        )
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        uses: actions/github-script@v3.1.0
        id: branch-name
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number,
            });

            return pullRequest.head.ref

      - name: Pull version from comment body
        run: |
          NEW_VERSION=$(echo ${{ github.event.comment.body }} | grep '/bump-version' | cut -d" " -f2)
          [[ "${NEW_VERSION}" =~ ^v[0-9].[0-9].[0-9]$ ]]
          echo "new_version=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ steps.branch-name.outputs.result }}

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Update Azure ARM template
        working-directory: scripts
        run: |
          python auto-version-bump.py $new_version

      - name: Add and commit updated file
        uses: EndBug/add-and-commit@v5
        with:
          add: 'azure.deploy.json'
          author_name: CI User
          author_email: ci-user@github.local
          message: "Update versions in Azure ARM template"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
