name: Run Setup

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Linux - Run setup.sh
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Execute setup.sh
        run: |
          chmod 700 setup.sh
          ./setup.sh
