name: Run Setup

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Linux - Run setup.sh
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Make shell scripts executable
        run: |
          chmod -x *.sh
      
      - name: Execute setup.sh
        run: |
          ./setup.sh
