name: Run Setup

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: ${{ matrix.os }} - Run setup.sh
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [
          linux,
          macos,
          windows
        ]
        include:
          - name: linux
            os: ubuntu-latest
          - name: macos
            os: macos-latest
          - name: windows
            os: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Test Windows
        if: runner.os == 'Windows'
        run: |
          echo $OSTYPE
        shell: bash

      - name: Execute setup.sh
        run: |
          chmod 700 setup.sh
          ./setup.sh
        shell: bash
