name: Shellcheck

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test sh scripts with Shellcheck on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install shellcheck
      - name: Run Shellcheck on all sh files in repo
        run: |
          shellcheck *.sh
