name: Run shellcheck and shfmt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shell-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run shell-checker
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: luizm/action-sh-checker@v0.1.3

      - name: Run shell-checker
        if: github.event.pull_request
        uses: luizm/action-sh-checker@v0.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sh_checker_comment: true
