name: Shellcheck

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  shellcheck:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install shellcheck
      - name: Run Shellcheck on all sh files in repo
        run: |
          shellcheck *.sh
