name: Run shellcheck and shfmt

on: [push, pull_request]

jobs:
  shell-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run shell-checker
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: luizm/action-sh-checker@master

      - name: Run shell-checker
        if: github.event.pull_request
        uses: luizm/action-sh-checker@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sh_checker_comment: true
