name: yamllint

on: [push, pull_request]

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run yamllint
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_file_or_dir: templates
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
